import type { ReactNode } from "react";
import Link from "@docusaurus/Link";
import Layout from "@theme/Layout";
import styles from "./start.module.css";

const stages = [["01", "Make your first request", "Run one small Claude call. Learn what a model, message, response, and token are.", "20 min", "/docs/labs/lab-1-first-call"], ["02", "Turn an answer into data", "Give Claude a schema so your code receives a classification it can safely use.", "35 min", "/docs/labs/lab-2-structured-outputs"], ["03", "Let Claude check facts", "Connect tools, watch the model ask for order and policy data, and inspect its trace.", "45 min", "/docs/labs/lab-3-tool-use"], ["04", "Make the experience feel alive", "Stream a response to the browser and handle the ending and error states correctly.", "30 min", "/docs/labs/lab-4-streaming"], ["05", "Learn to operate it", "Measure cost, caching, model choice, and safety before you call something production-ready.", "2–3 hrs", "/mission"]] as const;
const sample = 'const response = await client.messages.create({\n  model: "claude-opus-5",\n  max_tokens: 1024,\n  messages: [{ role: "user", content: "Explain zippers." }],\n});';

export default function StartPage(): ReactNode {
  return <Layout title="Start from zero" description="A beginner-safe path from your first Claude API call to a production-shaped feature."><main className="container"><section className={styles.hero}><p className={styles.eyebrow}>No prior API experience assumed</p><h1>Start with one Claude request. End ready to build.</h1><p className={styles.lead}>This is a hands-on path for developers who are new to Anthropic and the Claude API. You will run small pieces of real code, change one thing at a time, and learn why each production pattern exists before you need it.</p><div className={styles.promise}><div><strong>Start here</strong><span>Node, an API key, and curiosity. No AI background needed.</span></div><div><strong>Learn by changing</strong><span>Every stage gives you a small working change, not a lecture to memorize.</span></div><div><strong>Finish with judgment</strong><span>Use the mission to combine the patterns into a system you can explain.</span></div></div><Link className="button button--primary button--lg" to="/docs/labs/lab-1-first-call">Make your first request</Link></section><section className={styles.primer}><p className={styles.eyebrow}>The only mental model you need first</p><h2>You send messages; Claude sends a response.</h2><p>A model is the engine that generates the response. The SDK sends your request to Anthropic’s Messages API and gives your program a response object back.</p><pre className={styles.code}><code>{sample}</code></pre><div className={styles.anatomy}><div><b>model</b><span>Which Claude engine should answer.</span></div><div><b>messages</b><span>What your application asks Claude to do.</span></div><div><b>response</b><span>Content, stop reason, and token usage to inspect.</span></div></div></section><section className={styles.path}><p className={styles.eyebrow}>Your path</p><h2>Build confidence one working layer at a time.</h2><p className={styles.note}>Do these in order. Each step assumes only what the previous one taught.</p>{stages.map(([number, title, detail, time, to]) => <Link key={number} className={styles.stage} to={to}><span className={styles.number}>{number}</span><span><h3>{title}</h3><p>{detail}</p></span><span className={styles.time}>{time} →</span></Link>)}</section></main></Layout>;
}
