import type { ReactNode } from "react";
import OriginalDocCardList from "@theme-original/DocCardList";
import type { Props } from "@theme/DocCardList";
import LabPath from "@site/src/components/LabPath";

/**
 * The labs index gets a path; every other generated index keeps the grid.
 *
 * The /labs page is a generated-index, so its body is whatever DocCardList
 * renders. website/docs is generated by scripts/sync-docs.mjs and gitignored,
 * which rules out hand-writing an index.mdx in there, and swizzling the whole
 * generated-index page would mean re-implementing the breadcrumbs, title and
 * paginator to change one child. So the swap happens here: if the items are
 * the labs, render LabPath, otherwise delegate untouched.
 */

function isLabsList(items: Props["items"]): boolean {
  if (!items || items.length === 0) {
    return false;
  }
  return items.every(
    (item) =>
      item.type === "link" &&
      typeof item.docId === "string" &&
      item.docId.startsWith("labs/"),
  );
}

export default function DocCardList(props: Props): ReactNode {
  if (isLabsList(props.items)) {
    return <LabPath />;
  }
  return <OriginalDocCardList {...props} />;
}
