import type { ReactNode } from "react";
import useBaseUrl from "@docusaurus/useBaseUrl";
import styles from "./styles.module.css";

/**
 * Pictures for the deck, and where each one came from.
 *
 * TWO KINDS OF IMAGE, and the distinction matters for how they are treated:
 *
 * PHOTOGRAPHS are Unsplash, lifted from the shop's own catalogue so the deck
 * and the storefront show the same world rather than two stock-photo moods.
 * The Unsplash License asks for no credit; `storefront/lib/gear-images.ts`
 * explains at length why credit is given anyway, and the same reasoning
 * applies harder here — a slide is shown to a room. So a photo cannot be
 * rendered without its photographer, which is why the credit lives in this
 * record and not in the slide markup where it could be forgotten.
 *
 * SCREENSHOTS are stills of the live storefront, generated by
 * `storefront/scripts/talk-shots.mjs`. They are the reason these slides can
 * claim Northwind is real without asking the room to take it on faith. They
 * are also the part that rots: re-run that script when the shop changes.
 *
 * Both live in website/static/img/talk/ and are served by this site — never
 * hot-linked, same rule the storefront set.
 */

type Credit = { photographer: string; username: string };

const IMAGES: Record<string, { alt: string; credit?: Credit }> = {
  "hero-basecamp": {
    alt: "A low tent pitched on a rocky shoreline at sunrise, with mist over a lake and mountains behind.",
    credit: { photographer: "Daan Weijers", username: "daanweijers" },
  },
  "basecamp-bottle-32": {
    alt: "An insulated bottle and an enamel mug on frosted grass, mountains in the distance.",
    credit: { photographer: "Jisu Han", username: "makeitcount" },
  },
  "shop-home": {
    alt: "The Northwind Outfitters storefront home page: a tent at sunrise under the headline “Gear that outlasts the trip.”",
  },
  "support-form": {
    alt: "The storefront's contact form beside a diagram of the triage pipeline the message will travel.",
  },
  "escalation-queue": {
    alt: "The escalation queue board. One card is tagged safety and urgent: a child's illness linked to a flaking bottle lining, confidence 0.88.",
  },
};

function useImage(name: string) {
  const meta = IMAGES[name];
  if (!meta) throw new Error(`No image registered as "${name}"`);
  return { src: useBaseUrl(`/img/talk/${name}.jpg`), ...meta };
}

/** Photographer credit. Small, in the corner, never omitted. */
function Attribution({ credit }: { credit: Credit }): ReactNode {
  return (
    <span className={styles.credit}>
      Photo {credit.photographer} / Unsplash
    </span>
  );
}

/**
 * A photograph filling the whole slide, with the content over it.
 *
 * The scrim is not decoration: white text on an unmodified photograph is
 * unreadable the moment a projector lifts the black point, which it always
 * does. Pine at 0.72 keeps the slide inside the brand and keeps the type at
 * contrast whatever the room's projector does to the midtones.
 */
export function Backdrop({
  name,
  children,
}: {
  name: string;
  children: ReactNode;
}): ReactNode {
  const { src, alt, credit } = useImage(name);
  return (
    <div className={styles.backdrop}>
      <img className={styles.backdropImg} src={src} alt={alt} />
      <div className={styles.backdropBody}>{children}</div>
      {credit && <Attribution credit={credit} />}
    </div>
  );
}

/** A photograph as a panel beside the text, with an optional caption. */
export function Photo({
  name,
  caption,
}: {
  name: string;
  caption?: ReactNode;
}): ReactNode {
  const { src, alt, credit } = useImage(name);
  return (
    <figure className={styles.photo}>
      <img src={src} alt={alt} />
      {caption && <figcaption>{caption}</figcaption>}
      {credit && <Attribution credit={credit} />}
    </figure>
  );
}

/**
 * A screenshot of the live shop, in a frame that reads as a browser window
 * rather than as a photograph — the room needs to know at a glance that this
 * is a screen they could open themselves, not an illustration.
 */
export function Shot({
  name,
  caption,
}: {
  name: string;
  caption?: ReactNode;
}): ReactNode {
  const { src, alt } = useImage(name);
  return (
    <figure className={styles.shot}>
      <img src={src} alt={alt} />
      {caption && <figcaption>{caption}</figcaption>}
    </figure>
  );
}
