/**
 * Lab metadata for the /docs/labs landing page.
 *
 * WHY THIS IS HAND-MAINTAINED rather than read out of the lab frontmatter:
 * website/docs is generated by scripts/sync-docs.mjs and gitignored, and the
 * lab markdown is canonical in curriculum/ where it is also read on GitHub.
 * Adding phase names and one-line taglines to that markdown would put landing
 * page copy in the middle of the labs. So the labs own their content and this
 * file owns how the path through them is presented, the same split that
 * src/data/lab-videos.json already uses for YouTube ids.
 *
 * `minutes` and `requires` mirror the "Time / Prerequisites" line at the top
 * of each lab. If you change one, change the other.
 */

export type Lab = {
  /** Position in the sequence, and the number rendered on the rail. */
  n: number;
  /** Doc id under docs/labs, without the folder. */
  slug: string;
  /** Title without the "Lab N — " prefix; the rail carries the number. */
  title: string;
  /** One sentence on what the lab is actually for. Not a summary. */
  tagline: string;
  /** Minutes, from the lab's own Time line. */
  minutes: number;
  /** Lab numbers this one builds on. */
  requires: number[];
  /** A prerequisite that is not a lab, e.g. "Setup complete". */
  requiresText?: string;
  /** The route or API surface the lab introduces. Rendered as code. */
  tag: string;
  /** Labs a learner can do without an Anthropic key. */
  noKey?: boolean;
};

export type Phase = {
  label: string;
  blurb: string;
  labs: Lab[];
};

export const LAB_PATH: Phase[] = [
  {
    label: "Groundwork",
    blurb:
      "Before any prompt work: a number to measure against, and the four fields that price everything else.",
    labs: [
      {
        n: 0,
        slug: "lab-0-scoreboard",
        title: "Establish your evaluation baseline",
        tagline:
          "Hand-label three real tickets and record the score. Every change after this gets measured against that number.",
        minutes: 20,
        requires: [],
        requiresText: "Setup complete",
        tag: "baseline",
      },
      {
        n: 1,
        slug: "lab-1-first-call",
        title: "Your first call, and reading usage",
        tagline:
          "One call, four numbers. The usage block is the entire budget conversation, and it is invisible in the response body.",
        minutes: 20,
        requires: [],
        requiresText: "Node 20+, an Anthropic API key",
        tag: "usage",
      },
    ],
  },
  {
    label: "The four capabilities",
    blurb:
      "One route per idea. Each lab introduces exactly one new thing and builds on the one before it.",
    labs: [
      {
        n: 2,
        slug: "lab-2-structured-outputs",
        title: "Structured outputs and schema design",
        tagline:
          "A schema is where you decide what the system may say, what it must commit to, and how it is required to express doubt.",
        minutes: 35,
        requires: [1],
        tag: "POST /v1/triage",
      },
      {
        n: 3,
        slug: "lab-3-tool-use",
        title: "Tool use and the agentic loop",
        tagline:
          "The model looks up the order instead of believing the customer's account of it, and returns the trace that proves it did.",
        minutes: 45,
        requires: [2],
        tag: "POST /v1/resolve",
      },
      {
        n: 4,
        slug: "lab-4-streaming",
        title: "Streaming and SSE",
        tagline:
          "Tokens arrive as they are generated, proxies buffer them, and the error lands after the status code already said 200.",
        minutes: 30,
        requires: [1],
        tag: "POST /v1/draft",
      },
      {
        n: 5,
        slug: "lab-5-prompt-caching",
        title: "Prompt caching and cost",
        tagline:
          "The handbook goes out on every request. Caching takes that line from about $765 a month to about $75, and every way of breaking it fails silently.",
        minutes: 35,
        requires: [1, 2],
        tag: "cache_control",
      },
    ],
  },
  {
    label: "Judgment",
    blurb:
      "What belongs on the scoreboard, and which model is worth spending the budget on.",
    labs: [
      {
        n: 6,
        slug: "lab-6-evals",
        title: "Eval design and LLM-as-judge",
        tagline:
          "Write the cases you suspect will fail, starting with the one that opens “probably nothing,” then score what no assertion can.",
        minutes: 45,
        requires: [0, 2, 3],
        tag: "LLM-as-judge",
      },
      {
        n: 7,
        slug: "lab-7-choosing-a-model",
        title: "Choosing a model",
        tagline:
          "Measure before you downgrade. The five points a cheaper model gives up are disproportionately the cases that matter.",
        minutes: 45,
        requires: [0, 2, 6],
        tag: "POST /v1/estimate",
      },
    ],
  },
  {
    label: "Production",
    blurb: "The parts that separate a demo from a service someone depends on.",
    labs: [
      {
        n: 8,
        slug: "lab-8-trust-boundary",
        title: "The trust boundary",
        tagline:
          "A boolean the model wrote is not a permission check. Move the authority into code, then try to talk your way past it.",
        minutes: 60,
        requires: [0, 3, 6],
        tag: "prompt injection",
      },
      {
        n: 9,
        slug: "lab-9-shipping-it",
        title: "Shipping it",
        tagline:
          "Batches are half price and the measurement disagrees anyway. Rate limits, model pinning, and publishing tools to clients you did not write.",
        minutes: 60,
        requires: [0, 3, 5, 7],
        tag: "Batches API",
      },
      {
        n: 10,
        slug: "lab-10-ask-northwind",
        title: "Ask Northwind",
        tagline:
          "One assistant across the course and the shop, with narrow typed tools and the write held behind a human confirmation.",
        minutes: 45,
        requires: [3, 8],
        tag: "capstone",
        noKey: true,
      },
    ],
  },
];

/** Flat sequence, for lookups by number. */
export const ALL_LABS: Lab[] = LAB_PATH.flatMap((phase) => phase.labs);

export function labHref(lab: Lab): string {
  return `/docs/labs/${lab.slug}`;
}

/** Total run time across every lab, as "7h 20m". */
export function totalTime(): string {
  const total = ALL_LABS.reduce((sum, lab) => sum + lab.minutes, 0);
  const hours = Math.floor(total / 60);
  const minutes = total % 60;
  return minutes === 0 ? `${hours}h` : `${hours}h ${minutes}m`;
}
