/**
 * Generates the social cards for both public surfaces.
 *
 * WHY THIS EXISTS: a link posted to LinkedIn is judged before it is clicked.
 * The storefront shipped no openGraph metadata at all and the docs site was
 * still serving the stock Docusaurus card, so the first impression of both
 * was either a scraped fragment or somebody else's branding.
 *
 * WHY IT LIVES HERE: `sharp` is a storefront dependency. The docs site has no
 * image toolchain of its own and does not need one for two static files, so
 * this writes across into `website/static/img/` rather than duplicating the
 * dependency there.
 *
 * Run:  node scripts/og-cards.mjs   (from storefront/)
 *
 * The output is committed. It is regenerated by hand when the copy or the
 * palette changes, not on every build — a card that only changes twice a year
 * does not justify a build step on either project.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const HERE = dirname(fileURLToPath(import.meta.url));

const PINE = "#1f3d33";
const SPRUCE = "#5c9a86";
const BONE = "#f2ede4";
const EMBER = "#d9642a";

/** The header mark, scaled into a 64-unit box at an arbitrary origin. */
function mark(x, y, size) {
  const s = size / 64;
  return `<g transform="translate(${x} ${y}) scale(${s})">
    <rect width="64" height="64" rx="15" fill="${SPRUCE}" opacity="0.18"/>
    <path d="M42 26 L58 47 H30 Z" fill="${SPRUCE}"/>
    <path d="M26 16 L44 47 H8 Z" fill="${BONE}"/>
    <path d="M26 16 L32 26 L28.5 25 L26 28 L23 24.5 L20 26 Z" fill="${PINE}"/>
  </g>`;
}

/**
 * Text is drawn with an explicit font stack rather than a webfont: the card is
 * rasterised here, once, on a machine that has these faces, so there is no
 * loading path at view time to get wrong.
 */
const SANS = "Helvetica Neue, Helvetica, Arial, sans-serif";
const MONO = "SF Mono, Menlo, monospace";

function card({ eyebrow, title, lines, chips, accent }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#16302700"/>
      <stop offset="0%" stop-color="#163027"/>
      <stop offset="100%" stop-color="${PINE}"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#bg)"/>

  <!-- A single hairline of the accent along the top edge. LinkedIn crops the
       card's corners on some surfaces but never the top band. -->
  <rect x="0" y="0" width="1200" height="8" fill="${accent}"/>

  ${mark(80, 72, 64)}
  <text x="164" y="118" font-family="${SANS}" font-size="22" font-weight="700"
        letter-spacing="6" fill="${BONE}" opacity="0.75">${eyebrow}</text>

  <text x="80" y="286" font-family="${SANS}" font-size="76" font-weight="800"
        letter-spacing="-2" fill="${BONE}">${title}</text>

  ${lines
    .map(
      (line, i) =>
        `<text x="80" y="${356 + i * 46}" font-family="${SANS}" font-size="32"
               fill="${BONE}" opacity="0.82">${line}</text>`,
    )
    .join("\n  ")}

  ${chips
    .map((chip, i) => {
      // Monospace at 20px is ~12px per glyph; padding the box off the string
      // length keeps the chips from needing a text-measuring pass.
      const w = chip.length * 12 + 36;
      const x = 80 + chips.slice(0, i).reduce((acc, c) => acc + c.length * 12 + 36 + 14, 0);
      return `<g><rect x="${x}" y="524" width="${w}" height="44" rx="22"
                fill="${BONE}" opacity="0.10"/>
              <text x="${x + 18}" y="553" font-family="${MONO}" font-size="20"
                fill="${BONE}" opacity="0.88">${chip}</text></g>`;
    })
    .join("\n  ")}
</svg>`;
}

const CARDS = [
  {
    out: resolve(HERE, "../public/og.png"),
    svg: card({
      eyebrow: "NORTHWIND OUTFITTERS",
      title: "A shop that isn't real.",
      lines: [
        "Its support desk is. File a complaint and watch Claude",
        "read it, rank it, and decide whether a human sees it.",
      ],
      chips: ["no signup", "live model", "~2s"],
      accent: EMBER,
    }),
  },
  {
    out: resolve(HERE, "../../website/static/img/og-labs.png"),
    svg: card({
      eyebrow: "CLAUDE API LABS",
      title: "Build the thing, not a toy.",
      lines: [
        "One support-triage service, four routes, four capabilities.",
        "Read it, run it, break it, then ship your own.",
      ],
      chips: ["structured outputs", "tool use", "streaming", "evals"],
      accent: SPRUCE,
    }),
  },
];

for (const { out, svg } of CARDS) {
  const png = await sharp(Buffer.from(svg)).png().toBuffer();
  writeFileSync(out, png);
  console.log(`wrote ${out} (${(png.length / 1024).toFixed(0)} kB)`);
}
