/**
 * The repository's front door: a banner and a gallery for README.md.
 *
 * WHY THIS EXISTS: the storefront and the course site are branded, and the
 * README — the page most people actually see first, because it is what a link
 * to the repo resolves to — was five hundred lines of unbroken prose with no
 * picture of any kind. Someone arriving from a link could not see what they
 * would get. That is a presentation bug, and it is worth the same care as the
 * social cards.
 *
 * WHY IT LIVES HERE: `sharp` is a storefront dependency and the capture
 * helpers already live in scripts/lib. The output is written up into
 * assets/readme/ at the repo root, the way og-cards.mjs writes across into the
 * docs site.
 *
 * WHY THE GALLERY IS GENERATED RATHER THAN HAND-CAPTURED: a screenshot is a
 * fact with an expiry date. When a surface changes, the honest fix is to
 * re-run one command — not to reverse-engineer how somebody produced a PNG in
 * 2026. The output IS committed; this is regenerated by hand, like the OG
 * cards, not wired into a build.
 *
 * Run:  node scripts/readme-art.mjs        (from storefront/)
 *
 * Needs a Chrome. Set CHROME_BIN if yours is not in the usual place.
 */
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";
import { PINE, SPRUCE, BONE, EMBER, SANS, MONO, mark } from "./lib/brand.mjs";
import { capture, crop } from "./lib/capture.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "../../assets/readme");

const SHOP = process.env.SHOP_ORIGIN ?? "https://northwind.mlynn.dev";
const LABS = process.env.LABS_ORIGIN ?? "https://triage.mlynn.dev";

/**
 * Gallery images are displayed at about half a README's column width on a
 * desktop and less on a phone, so 1200 is already 2× what is shown. Going
 * wider costs repository weight and buys nothing.
 */
const GALLERY_WIDTH = 1200;

/* ------------------------------------------------------------------ banner */

/**
 * 2:1, because GitHub renders a README image at full column width and a
 * banner taller than that pushes the first sentence below the fold on a
 * laptop. The type is sized to survive being shown at 900px.
 */
function banner() {
  const chips = ["structured outputs", "tool use", "streaming", "caching", "evals"];
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="440" viewBox="0 0 1280 440">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#163027"/>
      <stop offset="100%" stop-color="${PINE}"/>
    </linearGradient>
  </defs>
  <rect width="1280" height="440" fill="url(#bg)"/>
  <rect x="0" y="0" width="1280" height="8" fill="${EMBER}"/>

  ${mark(80, 64, 60)}
  <text x="158" y="105" font-family="${SANS}" font-size="20" font-weight="700"
        letter-spacing="6" fill="${BONE}" opacity="0.7">NORTHWIND OUTFITTERS</text>

  <text x="80" y="228" font-family="${SANS}" font-size="72" font-weight="800"
        letter-spacing="-2" fill="${BONE}">Claude Triage API</text>

  <text x="80" y="284" font-family="${SANS}" font-size="28" fill="${BONE}" opacity="0.84">
    A support-triage service built on the Claude API — and the course that teaches it.
  </text>
  <text x="80" y="324" font-family="${SANS}" font-size="28" fill="${SPRUCE}">
    Written to be read and taught from, not just run.
  </text>

  ${chips
    .map((chip, i) => {
      // Monospace at 19px is ~11.4px per glyph; padding the box off the string
      // length keeps the chips from needing a text-measuring pass.
      const w = Math.round(chip.length * 11.4) + 34;
      const x =
        80 +
        chips
          .slice(0, i)
          .reduce((acc, c) => acc + Math.round(c.length * 11.4) + 34 + 12, 0);
      return `<g><rect x="${x}" y="368" width="${w}" height="42" rx="21"
                fill="${BONE}" opacity="0.10"/>
              <text x="${x + 17}" y="395" font-family="${MONO}" font-size="19"
                fill="${BONE}" opacity="0.86">${chip}</text></g>`;
    })
    .join("\n  ")}
</svg>`;
}

/* ----------------------------------------------------------------- gallery */

/**
 * One image per claim the README makes about itself. Each crop is chosen so
 * the thing being claimed is the thing you can read at half-column width —
 * see the note on `crop` in lib/capture.mjs.
 */
const GALLERY = [
  {
    name: "shop",
    url: `${SHOP}/`,
    viewport: [1440, 900],
    // "The scenario, made real": the shop exists and looks like a shop.
    rect: [0, 0, 1440, 560],
  },
  {
    name: "queue",
    url: `${SHOP}/queue`,
    viewport: [1440, 1400],
    // "Escalated tickets land in a reviewer queue": the safety card, tagged
    // and scored, is the whole argument in one element.
    rect: [712, 612, 580, 300],
  },
  {
    name: "playground",
    url: `${LABS}/playground/models`,
    viewport: [1440, 1400],
    dark: true,
    // "Seven interactive playgrounds": the model matrix rendering measured
    // results, not a screenshot of a paragraph about measured results. Starts
    // at the provenance bar and ends on a heading, so neither edge lands
    // mid-sentence or mid-row.
    rect: [0, 370, 1440, 390],
  },
  {
    name: "deck",
    url: `${LABS}/talk`,
    viewport: [1440, 1000],
    dark: true,
    // The slideshow, which nothing in the README currently mentions at all.
    // Stops just below the slide frame: the control row underneath crops into
    // a line of half-buttons that reads as a broken image.
    rect: [90, 55, 1260, 692],
  },
];

async function main() {
  mkdirSync(OUT, { recursive: true });

  const png = await sharp(Buffer.from(banner())).png().toBuffer();
  writeFileSync(join(OUT, "banner.png"), png);
  console.log(`banner.png  1280×440  (${(png.length / 1024).toFixed(0)} kB)`);

  const dir = mkdtempSync(join(tmpdir(), "readme-art-"));
  try {
    for (const shot of GALLERY) {
      const raw = capture({
        name: shot.name,
        url: shot.url,
        viewport: shot.viewport,
        dir,
        dark: shot.dark,
      });
      const { w, h } = await crop({
        from: raw,
        to: join(OUT, `${shot.name}.jpg`),
        rect: shot.rect,
        width: GALLERY_WIDTH,
      });
      console.log(`${shot.name}.jpg  ${w}×${h}  from ${shot.url}`);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

await main();
