/**
 * Stills of the storefront, for the intro talk's slides.
 *
 * WHY THIS EXISTS: the deck at /talk spends its first three slides asserting
 * that Northwind is a real-feeling company with a real support queue. Saying
 * so is weaker than showing it, and the shop is already built — so the slides
 * carry actual screens rather than diagrams of screens.
 *
 * WHY IT LIVES HERE: same reason as og-cards.mjs. `sharp` is a storefront
 * dependency; the docs site has no image toolchain and does not need one for
 * four static files, so this writes across into `website/static/img/talk/`.
 *
 * WHY IT IS A SCRIPT AND NOT FOUR COMMITTED PNGs: a screenshot is a fact with
 * an expiry date. When the shop's layout changes, the honest fix is to re-run
 * one command, not to reverse-engineer how somebody produced an image in
 * 2026. The output IS committed — this is regenerated by hand, like the OG
 * cards, not wired into a build.
 *
 * Run:  node scripts/talk-shots.mjs            (from storefront/)
 *       TALK_SHOT_ORIGIN=http://localhost:3000 node scripts/talk-shots.mjs
 *
 * Needs a Chrome. Set CHROME_BIN if yours is not in the usual place.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, copyFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const HERE = dirname(fileURLToPath(import.meta.url));
const STOREFRONT = resolve(HERE, "..");
const OUT = resolve(STOREFRONT, "../website/static/img/talk");

const ORIGIN = process.env.TALK_SHOT_ORIGIN ?? "https://northwind.mlynn.dev";

/** Retina, so a still holds up when a projector scales it back up. */
const SCALE = 2;
/** Long edge of what ships. The frame is 1200px at most; 1600 covers 2x. */
const WIDTH = 1600;

const CHROME_CANDIDATES = [
  process.env.CHROME_BIN,
  "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
  "/Applications/Chromium.app/Contents/MacOS/Chromium",
  "/usr/bin/google-chrome",
  "/usr/bin/chromium",
].filter(Boolean);

function chrome() {
  const found = CHROME_CANDIDATES.find((p) => existsSync(p));
  if (!found) {
    throw new Error(
      `No Chrome found. Set CHROME_BIN. Looked in:\n  ${CHROME_CANDIDATES.join("\n  ")}`,
    );
  }
  return found;
}

/**
 * Each shot names the viewport it is composed for and the slice of that
 * viewport worth keeping, in CSS pixels.
 *
 * THE CROPS ARE THE WHOLE JOB. A slide still is read from the back of a room
 * at maybe a third of the width it was captured at, so a full-page screenshot
 * arrives as grey texture — the first pass of this deck had a queue card
 * nobody past row three could read. Crop to the one element the slide is
 * about and it magnifies to legible at the same panel width. Cropping also
 * takes care of the "Ask Northwind" dock, which is fixed to the bottom-right
 * of every page and reads as a mistake in the corner of a slide.
 */
const SHOTS = [
  {
    name: "shop-home",
    path: "/",
    viewport: [1440, 900],
    // Banner, nav and the full hero. Stops above the fold's second section.
    crop: [0, 0, 1440, 580],
  },
  {
    name: "support-form",
    path: "/support",
    viewport: [1440, 900],
    // The compose box, from its label down to the Submit button. The pipeline
    // diagram beside it is lovely and completely illegible at slide size, so
    // it is cropped out and the slide says what it said. Kept close to the
    // queue card's proportions: two stills of very different heights on one
    // slide look like a layout accident.
    crop: [150, 238, 590, 400],
  },
  {
    name: "escalation-queue",
    path: "/queue",
    viewport: [1440, 1400],
    // One card: the safety ticket, tagged and scored. This is the payoff of
    // the whole first act, so it gets the magnification.
    crop: [712, 626, 580, 272],
  },
];

/**
 * Unsplash photography, lifted from the shop's own catalogue so the deck and
 * the storefront show the same world. Attribution rides along in
 * website/src/data/talk.tsx and renders on the slide — see the note at the
 * top of lib/gear-images.ts for why credit is given when the licence does not
 * demand it.
 */
const PHOTOS = ["hero-basecamp", "basecamp-bottle-32"];

function capture(shot, dir) {
  const [w, h] = shot.viewport;
  const png = join(dir, `${shot.name}.png`);
  execFileSync(
    chrome(),
    [
      "--headless",
      "--disable-gpu",
      "--hide-scrollbars",
      `--force-device-scale-factor=${SCALE}`,
      `--window-size=${w},${h}`,
      // Fonts, images and the client render all need to settle before the
      // shutter. Virtual time makes that deterministic instead of a sleep.
      "--virtual-time-budget=8000",
      `--screenshot=${png}`,
      `${ORIGIN}${shot.path}`,
    ],
    { stdio: "ignore" },
  );
  return png;
}

async function main() {
  mkdirSync(OUT, { recursive: true });
  const dir = mkdtempSync(join(tmpdir(), "talk-shots-"));

  try {
    for (const shot of SHOTS) {
      const png = capture(shot, dir);
      const [x, y, w, h] = shot.crop.map((n) => n * SCALE);
      const out = join(OUT, `${shot.name}.jpg`);
      await sharp(png)
        .extract({ left: x, top: y, width: w, height: h })
        .resize({ width: WIDTH, withoutEnlargement: true })
        .jpeg({ quality: 80, progressive: true, mozjpeg: true })
        .toFile(out);
      console.log(`${shot.name}.jpg  ${w}×${h} from ${ORIGIN}${shot.path}`);
    }

    for (const key of PHOTOS) {
      copyFileSync(
        resolve(STOREFRONT, "public/gear", `${key}.jpg`),
        join(OUT, `${key}.jpg`),
      );
      console.log(`${key}.jpg  copied from the shop`);
    }
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

await main();
