import useBaseUrl from "@docusaurus/useBaseUrl";
import type { ReactNode } from "react";

/**
 * "Listen to this lab" — a native <audio> element over an MP3 committed to
 * static/audio/ and generated by scripts/generate-audio.mjs.
 *
 * A plain element instead of a hosted widget on purpose: the narration is
 * static content, so serving it like any other asset means no third-party
 * script, no per-listen cost, and nothing that breaks when an external
 * service changes its embed.
 */
export default function AudioPlayer({ src }: { src: string }): ReactNode {
  return (
    <figure style={{ margin: "0 0 1.5rem" }}>
      <figcaption
        style={{
          fontSize: "0.75rem",
          fontWeight: 600,
          textTransform: "uppercase",
          letterSpacing: "0.05em",
          opacity: 0.7,
          marginBottom: "0.4rem",
        }}
      >
        Listen to this lab
      </figcaption>
      <audio
        controls
        preload="metadata"
        src={useBaseUrl(src)}
        style={{ width: "100%", display: "block" }}
      />
    </figure>
  );
}
