import demo from "@/data/demo-queue.json";
import type { EscalationDoc, QueueStats } from "./models";

/**
 * The public face of the escalation queue.
 *
 * Seven fictional tickets from `data/inbound-queue.json`, classified by the
 * real `/v1/triage` route and regenerated by `npm run sync:storefront`. They
 * are about nobody: `NW-T-10xx` are course fixtures, written to sit where two
 * handbook rules touch.
 *
 * They exist so `/queue` teaches something without a credential. Everything a
 * learner needs from that page — that `requires_human` routes somewhere, what
 * an escalation reason looks like, how the states move, that stored messages
 * are redacted — is demonstrable with representative tickets. None of it needs
 * a real person's support message, which is the thing that actually warrants
 * a token.
 *
 * Ids are prefixed `DEMO-` so a fixture can never be mistaken for a real
 * escalation in the UI or in a screenshot of it.
 */
export const DEMO_QUEUE = demo as unknown as EscalationDoc[];

export function demoStats(): QueueStats {
  const by = (s: string) => DEMO_QUEUE.filter((d) => d.status === s).length;
  return {
    depth: by("new"),
    claimed: by("claimed"),
    resolved: by("resolved"),
    // A plausible figure for a board that has clearly been worked, rather
    // than `null` — which would read as "the metric is broken" on a page whose
    // whole job is to show you what a working queue looks like.
    medianTimeToClaimSec: 41 * 60,
  };
}
