import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";
import { themes as prismThemes } from "prism-react-renderer";
import { readFileSync } from "node:fs";
import { STOREFRONT_URL, storefront } from "./src/urls";
import remarkQuiz from "./plugins/remark-quiz.mjs";

const GITHUB_ORG = process.env.DOCS_GITHUB_ORG ?? "mrlynn";
const GITHUB_REPO = process.env.DOCS_GITHUB_REPO ?? "claude-triage-api";
const GITHUB_REPO_URL = `https://github.com/${GITHUB_ORG}/${GITHUB_REPO}`;

/**
 * Deploy target decides the URL shape, and getting it wrong is the classic
 * "every asset 404s in production" bug.
 *
 *   Vercel      served at a domain root  -> baseUrl "/"
 *   GitHub Pages served at /<repo>/      -> baseUrl "/<repo>/"
 *
 * Vercel sets VERCEL=1 on every build, so the right values are picked
 * automatically and neither target needs a hand-edited config. Override
 * either one explicitly with DOCS_SITE_URL / DOCS_BASE_URL.
 */
/**
 * docs/ is generated, so a naive editUrl sends people to a path that does not
 * exist in the repo. sync-docs.mjs writes this manifest mapping each generated
 * page back to its canonical source.
 */
let DOC_SOURCES: Record<string, string> = {};
try {
  DOC_SOURCES = JSON.parse(readFileSync("./docs-manifest.json", "utf8"));
} catch {
  // Sync has not run yet. Edit links fall back to the repo root.
}

const ON_VERCEL = process.env.VERCEL === "1";

const VERCEL_URL =
  process.env.VERCEL_PROJECT_PRODUCTION_URL ?? process.env.VERCEL_URL;

const SITE_URL =
  process.env.DOCS_SITE_URL ??
  (ON_VERCEL && VERCEL_URL
    ? `https://${VERCEL_URL}`
    : ON_VERCEL
      ? "https://example.vercel.app"
      : `https://${GITHUB_ORG}.github.io`);

const BASE_URL =
  process.env.DOCS_BASE_URL ?? (ON_VERCEL ? "/" : `/${GITHUB_REPO}/`);

/**
 * Docs content is GENERATED into ./docs by scripts/sync-docs.mjs from the
 * markdown in the repo root. Edit the repo markdown, not ./docs.
 */
const config: Config = {
  title: "Claude Triage API",
  tagline: "A teaching-grade reference API for the Claude API",
  // Northwind mark — same asset as /brand. SVG for crisp tabs; ico kept as
  // a same-mark fallback for older agents that still request /img/favicon.ico.
  favicon: "img/brand/northwind-mark.svg",

  url: SITE_URL,
  baseUrl: BASE_URL,
  organizationName: GITHUB_ORG,
  projectName: GITHUB_REPO,

  // A broken link means a lab sends a learner to a 404 mid-exercise, so fail
  // the build rather than ship it.
  onBrokenLinks: "throw",

  markdown: {
    // Treat .md as CommonMark rather than MDX. The lab markdown contains
    // things like <customer_message> and bare braces that MDX would try to
    // parse as JSX and reject.
    format: "detect",
    mermaid: true,
    hooks: { onBrokenMarkdownLinks: "throw" },
  },

  themes: ["@docusaurus/theme-mermaid"],

  i18n: { defaultLocale: "en", locales: ["en"] },

  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "./sidebars.ts",
          remarkPlugins: [remarkQuiz],
          routeBasePath: "docs",
          editUrl: ({ docPath }) => {
            const source = DOC_SOURCES[docPath];
            return source
              ? `${GITHUB_REPO_URL}/edit/main/${source}`
              : GITHUB_REPO_URL;
          },
        },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Every page shared from here rendered the stock Docusaurus card, which
    // told a reader in a feed that this was somebody's generic docs site.
    // Generated by `storefront/scripts/og-cards.mjs` alongside the shop's, so
    // the two surfaces read as one thing when both land in the same feed.
    image: "img/og-labs.png",
    colorMode: { defaultMode: "dark", respectPrefersColorScheme: true },
    navbar: {
      title: "Claude Triage API",
      items: [
        { type: "doc", docId: "intro", position: "left", label: "Overview" },
        { type: "doc", docId: "scenario", position: "left", label: "Scenario" },
        { type: "doc", docId: "setup", position: "left", label: "Setup" },
        { type: "doc", docId: "concept-map", position: "left", label: "Concepts" },
        { to: "/start", position: "left", label: "Start from zero" },
        { type: "doc", docId: "glossary", position: "left", label: "Glossary" },
        {
          type: "docSidebar",
          sidebarId: "courseSidebar",
          position: "left",
          label: "Labs",
        },
        { type: "doc", docId: "architecture", position: "left", label: "Architecture" },
        { to: "/playground", position: "left", label: "Playground" },
        { to: "/mission", position: "left", label: "Mission" },
        { to: "/assessment", position: "left", label: "Assessment" },
        {
          href: STOREFRONT_URL,
          position: "right",
          label: "Northwind store",
        },
        {
          href: GITHUB_REPO_URL,
          label: "GitHub",
          position: "right",
        },
      ],
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Course",
          items: [
            { label: "The scenario", to: "/docs/scenario" },
            { label: "Northwind brand", to: "/brand" },
            { label: "The inbound queue", to: "/playground/queue" },
            { label: "Ops dashboard", href: storefront("/ops") },
            { label: "Visit the storefront", href: STOREFRONT_URL },
            { label: "Setup", to: "/docs/setup" },
            { label: "Concept map", to: "/docs/concept-map" },
            { label: "Glossary", to: "/docs/glossary" },
            { label: "Lab 1", to: "/docs/labs/lab-1-first-call" },
            { label: "Assessment", to: "/assessment" },
            { label: "Playground", to: "/playground" },
            { label: "Northwind mission", to: "/mission" },
          ],
        },
        {
          title: "Teaching",
          items: [
            { label: "Instructor guide", to: "/docs/instructor-guide" },
            { label: "Architecture", to: "/docs/architecture" },
          ],
        },
        {
          title: "Reference",
          items: [
            { label: "Claude API docs", href: "https://docs.claude.com" },
            { label: "Console", href: "https://console.anthropic.com" },
          ],
        },
      ],
    },
    prism: {
      // github is near-neutral and sits fine on Bone. dracula was the default
      // and is purple/pink — on a pine-and-spruce palette it read as a
      // different site pasted into the middle of the page. oceanicNext is
      // muted and slightly desaturated, and custom.css puts both on the site's
      // own surface colour so a page never carries two competing grounds.
      theme: prismThemes.github,
      darkTheme: prismThemes.oceanicNext,
      additionalLanguages: ["bash", "json", "typescript"],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
