import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * One hand-built sidebar rather than autogenerated, because the reading order
 * is the pedagogy. Concepts before labs, labs in sequence, solutions collapsed
 * so a learner does not trip over the answers on the way to Lab 1, and the
 * instructor material last.
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [
    "intro",
    "scenario",
    "setup",
    "concept-map",
    {
      type: "category",
      label: "Labs",
      collapsed: false,
      link: { type: "generated-index", title: "Labs", slug: "/labs" },
      items: [
        "labs/lab-1-first-call",
        "labs/lab-2-structured-outputs",
        "labs/lab-3-tool-use",
        "labs/lab-4-streaming",
        "labs/lab-5-prompt-caching",
        "labs/lab-6-evals",
      ],
    },
    "architecture",
    {
      type: "category",
      label: "For instructors",
      collapsed: true,
      items: ["instructor-guide", "assessment"],
    },
    {
      type: "category",
      label: "Solutions",
      collapsed: true,
      link: {
        type: "generated-index",
        title: "Solutions",
        description:
          "Answers to every lab question. Work the lab first, then check.",
        slug: "/solutions",
      },
      items: [
        "solutions/lab-1",
        "solutions/lab-2",
        "solutions/lab-3",
        "solutions/lab-4",
        "solutions/lab-5",
        "solutions/lab-6",
      ],
    },
  ],
};

export default sidebars;
