import type {
  PropSidebarItem,
  SidebarsConfig,
} from "@docusaurus/plugin-content-docs";
import type { SidebarIconName } from "./src/components/SidebarIcon";

/**
 * One hand-built sidebar rather than autogenerated, because the reading order
 * is the pedagogy. Concepts before labs, labs in sequence, solutions collapsed
 * so a learner does not trip over the answers on the way to Lab 1, and the
 * instructor material last.
 *
 * Icons live on top-level items and category headers only — nested lab and
 * solution links stay text so the sidebar stays a table of contents.
 */
function doc(id: string, icon: SidebarIconName): PropSidebarItem {
  return { type: "doc", id, customProps: { icon } };
}

const sidebars: SidebarsConfig = {
  courseSidebar: [
    doc("intro", "compass"),
    doc("scenario", "map"),
    doc("setup", "wrench"),
    doc("concept-map", "network"),
    doc("glossary", "library"),
    {
      type: "category",
      label: "Labs",
      collapsed: false,
      customProps: { icon: "flask" },
      link: { type: "generated-index", title: "Labs", slug: "/labs" },
      items: [
        "labs/lab-0-scoreboard",
        "labs/lab-1-first-call",
        "labs/lab-2-structured-outputs",
        "labs/lab-3-tool-use",
        "labs/lab-4-streaming",
        "labs/lab-5-prompt-caching",
        "labs/lab-6-evals",
        "labs/lab-7-choosing-a-model",
        "labs/lab-8-trust-boundary",
        "labs/lab-9-shipping-it",
        "labs/lab-10-ask-northwind",
      ],
    },
    doc("comparison", "compare"),
    doc("next-steps", "arrow"),
    doc("architecture", "boxes"),
    doc("python-deltas", "terminal"),
    {
      type: "category",
      label: "For instructors",
      collapsed: true,
      customProps: { icon: "graduation" },
      items: ["instructor-guide", "run-of-show", "assessment", "facilitator-keys"],
    },
    {
      type: "category",
      label: "Solutions",
      collapsed: true,
      customProps: { icon: "key" },
      link: {
        type: "generated-index",
        title: "Solutions",
        description:
          "Answers to every lab question. Work the lab first, then check.",
        slug: "/solutions",
      },
      items: [
        "solutions/lab-0",
        "solutions/lab-1",
        "solutions/lab-2",
        "solutions/lab-3",
        "solutions/lab-4",
        "solutions/lab-5",
        "solutions/lab-6",
        "solutions/lab-7",
        "solutions/lab-8",
        "solutions/lab-9",
        "solutions/lab-10",
      ],
    },
  ],
};

export default sidebars;
